version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www/html:/var/www/html
    depends_on:
      - php
    networks:
      - lamptest

  php:
    build: ./php
    volumes:
      - ./www/html:/var/www/html
    depends_on:
      - db
    networks:
      - lamptest

  db:
    image: mysql:8.0
    ports:
      - 13306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - lamptest

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    depends_on:
      - db
    networks:
      - lamptest

networks:
  lamptest:
    external: true